# *Numpy*

[This](https://www.youtube.com/watch?v=QUT1VHiLmmI) is a good video covering all the basics of numpy. 

I have written some code below for some important operations. (video is optional if you can just skim through the code)

**Import the numpy library**

This statement is to import library (pre written code) into our workspace.

In [6]:
import numpy as np
import pandas as pd

**Basic numpy operations**

In [16]:
# making an array from a python list
# generic syntax np.array(<array>)

a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [17]:
# gives shape
print(a1.shape)

(5,)


In [18]:
# gives number of elements
print(a1.size)

5


In [ ]:
# indexing and slicing the array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# returns number of dimensions
print(a2.ndim)
print(a1.ndim)

2
1


In [19]:
# to copy the array
a3 = a1 # do not do this (as it is a pass by refernece)
a3 = a1.copy() # do this

**Operations for indexing and slicing**

In [ ]:
# indexing for a 1-D array its similar to c++
print(a1[1])
print(a1[-1]) # -1 index refers to the last element, -2 means 2nd last etc

2
5


In [ ]:
# indexing is array[row, column]
print(a2[1, 2])

6


In [ ]:
# slicing is the same as a python list, i.e array[start:stop+1:stepsize]
print(a1[:]) # leaving something blank is taken as the min/max possible value
print(a1[0:3])
print(a1[4::-1]) # try 0:5:2

[1 2 3 4 5]
[1 2 3]
[5 4 3 2 1]


In [ ]:
# slicing is similar to python list and all the things done before work
print(a2[1,:]) # 2nd row
print(a2[:,1]) # 2nd column

[4 5 6]
[2 5]


**Initializing arrays**

In [ ]:
array_zeros = np.zeros((5,5))
print(array_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
array_ones = np.ones((2,4))
print(array_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
array_full = np.full((3,4),5)
print(array_full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# for a randomly intiliazed array
random_array = np.random.rand(2,3)
print(random_array)
# for a random integer array
randomint_array = np.random.randint(-5,5, size= (2,2))
print(randomint_array)

[[0.304777   0.35411275 0.14978901]
 [0.02579297 0.2783211  0.50037246]]
[[ 3  1]
 [ 4 -4]]


In [ ]:
# for an indentity matrix
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# To repeat an array
arr = np.array([[1,2]])
print(np.repeat(arr, 4, axis= 0))
arr1 = np.array([[1],[2]])
print(np.repeat(arr1, 4, axis= 1))
# axis 0 implies the first dimension (the rows) and axis 1 is the second dimension (the columns)

[[1 1 1 1 2 2 2 2]]
[[1 1 1 1]
 [2 2 2 2]]


**Algebra**

In [3]:
a = np.array([1,2,3,4,5,6])
print(a + 2) # try -, *, / and ** and see what happens

[3 4 5 6 7 8]


In [4]:
# adding two arrays
b = np.array([6,7,8,9,10,11])
print(a+b)

[ 7  9 11 13 15 17]


# *Pandas*

**How to read data from a .csv file**

[file used](https://drive.google.com/file/d/1W_wbWH7NFfaoy-McRFHNiEIJh22oVlqQ/view?usp=sharing)


In [13]:
# reading the data
dataset = pd.read_csv('test.csv')
dataset[:][0:10] # this is a dataframe

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0           1        337          118  ...  9.65         1             0.92
1           2        324          107  ...  8.87         1             0.76
2           3        316          104  ...  8.00         1             0.72
3           4        322          110  ...  8.67         1             0.80
4           5        314          103  ...  8.21         0             0.65
5           6        330          115  ...  9.34         1             0.90
6           7        321          109  ...  8.20         1             0.75
7           8        308          101  ...  7.90         0             0.68
8           9        302          102  ...  8.00         0             0.50
9          10        323          108  ...  8.60         0             0.45

[10 rows x 9 columns]

In [10]:
# generally we want to use arrays and not dataframes so we use
array = dataset[['University Rating']].values # returns an array
array[0:10]

array([[4],
       [4],
       [3],
       [3],
       [2],
       [5],
       [3],
       [2],
       [1],
       [3]])

In [12]:
array = dataset[['GRE Score'    ,'TOEFL Score'	,'University Rating']].values
array[:][0:10]

array([[337, 118,   4],
       [324, 107,   4],
       [316, 104,   3],
       [322, 110,   3],
       [314, 103,   2],
       [330, 115,   5],
       [321, 109,   3],
       [308, 101,   2],
       [302, 102,   1],
       [323, 108,   3]])